name: custommarker
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.1.10
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  build_runner: ^2.2.0
  flutter_cache_manager: ^3.3.0
  

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

